### ISSUE TITLE
vim-buffergator

### ISSUE THREAD

**Issue by JulioJu** [18z/VIM-tips#8]
Hi, thinks for your list !

Maybe you can add [vim buffergator](https://github.com/jeetsukumaran/vim-buffergator) ? It is newer than [minibufexplorer](https://github.com/fholgado/minibufexpl.vim/blob/master/doc/minibufexpl.txt) ! Furthermore it's currently in developpement,  [minibufexplorer](https://github.com/fholgado/minibufexpl.vim/blob/master/doc/minibufexpl.txt) isn't stil active.

**Comment by SSARCandy** [comment]
thanks for your suggestion! 👍
