### ISSUE TITLE
Vim tabber

### ISSUE THREAD

**Issue by JulioJu** [18z/VIM-tips#9]
Hi !

I also recently discovered  [Vim Tabber](https://github.com/fweep/vim-tabber). Maybe you can add it on your list ? It's very beautiful for tab number, and navigate between tabs with `[number]gt` (e.g `3gt`). Furthermore, it's prettier than the default Vim tab line !

**Comment by SSARCandy** [comment]
nice! thanks a lot

**Comment by 18z** [comment]
@JulioJu thanks :+1:
